source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

# Gems used only for assets and not required
# in production environments by default.
group :assets do

  gem 'sass-rails'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'

  gem 'bootstrap-sass'

end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

# all related to rails_admin
# gem 'rails3-generators'

gem 'activeadmin'
gem "meta_search",    '>= 1.1.0.pre'

gem 'rspec-rails', :group => [:test, :development]
gem 'factory_girl_rails'
group :test do
  gem 'capybara'
  gem 'guard-rspec'
  gem 'rb-inotify', '~> 0.8.8'
  gem 'spork'
  gem "guard-spork"
end
	
# irb tool
gem 'hirb', group: :development

gem 'inherited_resources'

gem 'simple_form'
gem 'country_select'

gem 'rabl'

